Ft about
supportingami/sami-website pull request #82
Opened 2022-08-29 07:22 UTC by KingMike100

#### What does this PR do?
- The **About** Page and its components( **Annual Reports and Members**) have been set up. 
- Emphasis put on data fetching so no CSS design at this point

#### Is this change ready to hit production in its current state?
- [ ] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):

- [ ] I consider this code done
- [ ] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* git checkout main
* git pull origin
* git checkout origin/ft-about
* yarn start

#### What are the relevant tickets?
- None

#### Screenshots (optional)
<img width="989" alt="Screenshot 2022-08-29 at 10 14 11" src="https://user-images.githubusercontent.com/24493616/187145188-0e14e4e3-fa26-4a7c-8db8-52d7acf647a1.png">

2022-08-29 11:50 UTC, chrismclarke requested changes
Thanks @KingMike100 and welcome back to the repo! Hopefully all the changes to the graphql workflows aren't too confusing (looks like you've implemented the endpoints all correctly so definitely a good sign)

As for the changes here, all look good to me. One small request is to please make the annual reports downloadable. You can see how similar file download functionality was added to the Resources page and query

2022-08-30 18:50 UTC, KingMike100 commented
@chrismclarke I've made the changes regarding downloading the annual reports and also added some export csv data

2022-08-31 08:26 UTC, chrismclarke commented
Many thanks @KingMike100 
I noticed that we currently don't have a way to share uploaded media (backend upload folder is in gitignore) so I get some small errors when running locally. I've added a better catch for these errors and I'll remove from gitignore, upload some correct media files. But otherwise looks good to me!

2022-08-31 08:56 UTC, chrismclarke approved these changes

2022-08-31 08:56 UTC, merged